<?php

/**
 * @file
 * Generate a submission key based on a webform submission ID
 */

define('WEBFORM_SIDKEY_DEFAULT_BASE', '16');

/**
 * Implements hook_permission().
 */
function webform_sidkey_permission() {
  return array(
    'configure webform_sidkey' =>  array(
      'title' => t('Configure Webform Submission Key'),
      'description' => t('Define the submission key settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function webform_sidkey_menu() {
  $items = array();

  $items['admin/config/content/webform/sidkey'] = array(
    'title' => 'Submission Key Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_sidkey_admin_form'),
    'access arguments' => array('configure webform_sidkey'),
    'file' => 'webform_sidkey.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_token_info_alter().
 */
function webform_sidkey_token_info_alter(&$data) {
  $data['tokens']['submission']['sidkey'] = array(
    'name' => t('Submission Key'),
    'description' => t('Unique, generated human readable key'),
  );
}

/**
 * Implements hook_tokens().
 */
function webform_sidkey_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'submission' && !empty($data['webform-submission'])) {
    $submission = $data['webform-submission'];
    if (isset($submission->sidkey)) {
      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'sidkey':
          $replacements[$original] = $submission->sidkey;
          break;
        }
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_webform_submission_load().
 */
function webform_sidkey_webform_submission_load(&$submissions) {
  foreach($submissions as $sid => $submission) {
    $submissions[$sid]->sidkey = webform_sidkey_generate_sidkey($sid);
  }
}

/**
 * Load submissions by sidkey value
 *
 * Wrapper function around webform_get_submissions() to load by sidkey
 * value.
 *
 * @see webform_get_submissions().
 */
function webform_sidkey_get_submissions($filters = array(), $headers = NULL, $pager_count = 0) {
  module_load_include('inc', 'webform', 'includes/webform.submissions');

  if (array_key_exists('sidkey', $filters)) {
    $filters['sid'] = webform_sidkey_extract_sid($filters['sidkey']);
    // Remove the sidkey to avoid confusing the webform submission loading code
    unset($filters['sidkey']);
  }

  return webform_get_submissions($filters, $headers, $pager_count);
}

/**
 * Generate a sidkey value based on a submission id
 *
 * @param int $sid
 *  Submission id
 * @return string
 *  Returns the generated key.
 */
function webform_sidkey_generate_sidkey($sid) {
  // @todo add the generated sid value to the loaded object
  $tobase = variable_get('webform_sidkey_default_base', WEBFORM_SIDKEY_DEFAULT_BASE);

  return base_convert($sid, 10, $tobase);
}

/**
 * Retrieve the sid value given a sidkey
 *
 * @param string $sidkey
 *  Sidkey value
 * @param int $frombase [optional]
 *  Base value for sidkey
 */
function webform_sidkey_extract_sid($sidkey, $frombase = NULL) {
  if (!is_int($frombase)) {
    $frombase = variable_get('webform_sidkey_default_base', WEBFORM_SIDKEY_DEFAULT_BASE);
  }
  return base_convert($sidkey, $frombase, 10);
}

/**
 * Implements hook_views_api().
 */
function webform_sidkey_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_data_alter().
 */
function webform_sidkey_views_data_alter(&$data) {
  if (isset($data['webform_submissions'])) {
    $data['webform_submissions']['sid']['field']['handler'] = 'webform_sidkey_views_hanlder_field_sidkey';
  }
}

// @todo move this into it's own file under views/handlers
class webform_sidkey_views_hanlder_field_sidkey extends views_handler_field_numeric {
  function option_definition() {
    $options = parent::option_definition();

    $options['submission_key'] = array('default' => FALSE, 'bool' => TRUE);

    return $options;
  }

  function options_form(&$form, &$form_state) {
    $form['submission_key'] = array(
      '#type' => 'checkbox',
      '#title' => t('Submission Key'),
      '#description' => t('Render the value as a submission key'),
      '#default_value' => $this->options['submission_key'],
    );

    parent::options_form($form, $form_state);
  }

  function render($values) {
    if (!empty($this->options['submission_key'])) {
      return webform_sidkey_generate_sidkey(intval($this->get_value($values)));
    }
    else {
      return parent::render($values);
    }
  }
}