<?php

/**
 * @file
 * Generate a submission key based on a webform submission ID
 */

define('WEBFORM_SIDKEY_DEFAULT_BASE', '16');

/**
 * Implements hook_permission().
 */
function webform_sidkey_permission() {
  return array(
    'configure webform_sidkey' =>  array(
      'title' => t('Configure Webform Submission Key'),
      'description' => t('Define the submission key settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function webform_sidkey_menu() {
  $items = array();

  $items['admin/config/content/webform/sidkey'] = array(
    'title' => 'Submission Key Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_sidkey_admin_form'),
    'access arguments' => array('configure webform_sidkey'),
    'file' => 'webform_sidkey.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}



/**
 * Implements hook_webform_submission_load().
 */
function webform_sidkey_webform_submission_load(&$submissions) {
  // @todo add the generated sid value to the loaded object
  $tobase = variable_get('webform_sidkey_default_base', WEBFORM_SIDKEY_DEFAULT_BASE);

  foreach($submissions as $sid => $submission) {
    $submissions[$sid]['sidkey'] = base_convert($sid, 10, $tobase);
  }
}

/**
 * Load submissions by sidkey value
 *
 * Wrapper function around webform_get_submissions() to load by sidkey
 * value.
 *
 * @see webform_get_submissions().
 */
function webform_sidkey_get_submissions($filters = array(), $headers = NULL, $pager_count = 0) {
  if (array_key_exists('sidkey', $filters)) {
    $frombase = variable_get('webform_sidkey_default_base', WEBFORM_SIDKEY_DEFAULT_BASE);
    $filters['sid'] = base_convert($filters['sidkey'], $frombase, 10);
  }

  return webform_get_submissions($filters, $headers, $pager_count);
}